import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.MolecularBiologyMrnaSurveillanceFoundationCanonicalLaneLean.MrnaSurveillanceBridgeLemmas
import HautevilleHouse.MolecularBiologyMrnaSurveillanceFoundationCanonicalLaneLean.MrnaSurveillanceGateLemmas

namespace HautevilleHouse
namespace MolecularBiologyMrnaSurveillanceFoundationCanonicalLaneLean

def ConstrainedMrnaSurveillanceClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_mrna_surveillance_endgame (A : AdmissibleClass) : ConstrainedMrnaSurveillanceClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end MolecularBiologyMrnaSurveillanceFoundationCanonicalLaneLean
end HautevilleHouse
